server:
  port: 80

spring:
  application:
    name: cloud-order-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#      defaultZone: http://localhost:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
